spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url:
     username:
     password:
  druid:
     initial-size: 5 #连接池初始化大小
     min-idle: 10 #最小空闲连接数
     max-active: 20 #最大连接数