spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://47.100.187.197 :3306/achieveit?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
     username: user
     password: archieveit
  druid:
     initial-size: 5 #连接池初始化大小
     min-idle: 10 #最小空闲连接数
     max-active: 20 #最大连接数